export const countriesList = [
  { name: "Afghanistan", phone: ["+93"], shortName: "AF", phoneLength: [9] },
  { name: "Albania", phone: ["+355"], shortName: "AL", phoneLength: [9] },
  { name: "Algeria", phone: ["+213"], shortName: "DZ", phoneLength: [9] },
  { name: "Andorra", phone: ["+376"], shortName: "AD", phoneLength: [6] },
  { name: "Angola", phone: ["+244"], shortName: "AO", phoneLength: [9] },
  { name: "Antigua and Barbuda", phone: ["+1-268"], shortName: "AG", phoneLength: [10] },
  { name: "Argentina", phone: ["+54"], shortName: "AR", phoneLength: [10] },
  { name: "Armenia", phone: ["+374"], shortName: "AM", phoneLength: [8] },
  { name: "Australia", phone: ["+61"], shortName: "AU", phoneLength: [9] },
  { name: "Austria", phone: ["+43"], shortName: "AT", phoneLength: [10] },
  { name: "Azerbaijan", phone: ["+994"], shortName: "AZ", phoneLength: [9] },
  { name: "Bahamas", phone: ["+1-242"], shortName: "BS", phoneLength: [10] },
  { name: "Bahrain", phone: ["+973"], shortName: "BH", phoneLength: [8] },
  { name: "Bangladesh", phone: ["+880"], shortName: "BD", phoneLength: [10] },
  { name: "Barbados", phone: ["+1-246"], shortName: "BB", phoneLength: [10] },
  { name: "Belarus", phone: ["+375"], shortName: "BY", phoneLength: [9] },
  { name: "Belgium", phone: ["+32"], shortName: "BE", phoneLength: [9] },
  { name: "Belize", phone: ["+501"], shortName: "BZ", phoneLength: [7] },
  { name: "Benin", phone: ["+229"], shortName: "BJ", phoneLength: [8] },
  { name: "Bhutan", phone: ["+975"], shortName: "BT", phoneLength: [8] },
  { name: "Bolivia", phone: ["+591"], shortName: "BO", phoneLength: [8] },
  { name: "Bosnia and Herzegovina", phone: ["+387"], shortName: "BA", phoneLength: [8] },
  { name: "Botswana", phone: ["+267"], shortName: "BW", phoneLength: [8] },
  { name: "Brazil", phone: ["+55"], shortName: "BR", phoneLength: [11] },
  { name: "Brunei", phone: ["+673"], shortName: "BN", phoneLength: [7] },
  { name: "Bulgaria", phone: ["+359"], shortName: "BG", phoneLength: [9] },
  { name: "Burkina Faso", phone: ["+226"], shortName: "BF", phoneLength: [8] },
  { name: "Burundi", phone: ["+257"], shortName: "BI", phoneLength: [8] },
  { name: "Cabo Verde", phone: ["+238"], shortName: "CV", phoneLength: [7] },
  { name: "Cambodia", phone: ["+855"], shortName: "KH", phoneLength: [8] },
  { name: "Cameroon", phone: ["+237"], shortName: "CM", phoneLength: [8] },
  { name: "Canada", phone: ["+1"], shortName: "CA", phoneLength: [10] },
  { name: "Central African Republic", phone: ["+236"], shortName: "CF", phoneLength: [8] },
  { name: "Chad", phone: ["+235"], shortName: "TD", phoneLength: [8] },
  { name: "Chile", phone: ["+56"], shortName: "CL", phoneLength: [9] },
  { name: "China", phone: ["+86"], shortName: "CN", phoneLength: [11] },
  { name: "Colombia", phone: ["+57"], shortName: "CO", phoneLength: [10] },
  { name: "Comoros", phone: ["+269"], shortName: "KM", phoneLength: [7] },
  { name: "Congo (Brazzaville)", phone: ["+242"], shortName: "CG", phoneLength: [7] },
  { name: "Congo (Kinshasa)", phone: ["+243"], shortName: "CD", phoneLength: [9] },
  { name: "Costa Rica", phone: ["+506"], shortName: "CR", phoneLength: [8] },
  { name: "Croatia", phone: ["+385"], shortName: "HR", phoneLength: [9] },
  { name: "Cuba", phone: ["+53"], shortName: "CU", phoneLength: [8] },
  { name: "Cyprus", phone: ["+357"], shortName: "CY", phoneLength: [8] },
  { name: "Czech Republic", phone: ["+420"], shortName: "CZ", phoneLength: [9] },
  { name: "Denmark", phone: ["+45"], shortName: "DK", phoneLength: [8] },
  { name: "Djibouti", phone: ["+253"], shortName: "DJ", phoneLength: [8] },
  { name: "Dominica", phone: ["+1-767"], shortName: "DM", phoneLength: [10] },
  { name: "Dominican Republic", phone: ["+1-809", "+1-829", "+1-849"], shortName: "DO", phoneLength: [10] },
  { name: "Ecuador", phone: ["+593"], shortName: "EC", phoneLength: [9] },
  { name: "Egypt", phone: ["+20"], shortName: "EG", phoneLength: [10] },
  { name: "El Salvador", phone: ["+503"], shortName: "SV", phoneLength: [8] },
  { name: "Equatorial Guinea", phone: ["+240"], shortName: "GQ", phoneLength: [7] },
  { name: "Eritrea", phone: ["+291"], shortName: "ER", phoneLength: [7] },
  { name: "Estonia", phone: ["+372"], shortName: "EE", phoneLength: [7] },
  { name: "Eswatini", phone: ["+268"], shortName: "SZ", phoneLength: [8] },
  { name: "Ethiopia", phone: ["+251"], shortName: "ET", phoneLength: [9] },
  { name: "Fiji", phone: ["+679"], shortName: "FJ", phoneLength: [7] },
  { name: "Finland", phone: ["+358"], shortName: "FI", phoneLength: [10] },
  { name: "France", phone: ["+33"], shortName: "FR", phoneLength: [9] },
  { name: "Gabon", phone: ["+241"], shortName: "GA", phoneLength: [8] },
  { name: "Gambia", phone: ["+220"], shortName: "GM", phoneLength: [7] },
  { name: "Georgia", phone: ["+995"], shortName: "GE", phoneLength: [9] },
  { name: "Germany", phone: ["+49"], shortName: "DE", phoneLength: [11] },
  { name: "Ghana", phone: ["+233"], shortName: "GH", phoneLength: [9] },
  { name: "Greece", phone: ["+30"], shortName: "GR", phoneLength: [10] },
  { name: "Grenada", phone: ["+1-473"], shortName: "GD", phoneLength: [10] },
  { name: "Guatemala", phone: ["+502"], shortName: "GT", phoneLength: [8] },
  { name: "Guinea", phone: ["+224"], shortName: "GN", phoneLength: [8] },
  { name: "Guinea-Bissau", phone: ["+245"], shortName: "GW", phoneLength: [7] },
  { name: "Guyana", phone: ["+592"], shortName: "GY", phoneLength: [7] },
  { name: "Haiti", phone: ["+509"], shortName: "HT", phoneLength: [8] },
  { name: "Honduras", phone: ["+504"], shortName: "HN", phoneLength: [8] },
  { name: "Hungary", phone: ["+36"], shortName: "HU", phoneLength: [9] },
  { name: "Iceland", phone: ["+354"], shortName: "IS", phoneLength: [7] },
  { name: "India", phone: ["+91"], shortName: "IN", phoneLength: [10] },
  { name: "Indonesia", phone: ["+62"], shortName: "ID", phoneLength: [10] },
  { name: "Iran", phone: ["+98"], shortName: "IR", phoneLength: [10] },
  { name: "Iraq", phone: ["+964"], shortName: "IQ", phoneLength: [10] },
  { name: "Ireland", phone: ["+353"], shortName: "IE", phoneLength: [9] },
  { name: "Israel", phone: ["+972"], shortName: "IL", phoneLength: [9] },
  { name: "Italy", phone: ["+39"], shortName: "IT", phoneLength: [11] },
  { name: "Jamaica", phone: ["+1-876"], shortName: "JM", phoneLength: [10] },
  { name: "Japan", phone: ["+81"], shortName: "JP", phoneLength: [11] },
  { name: "Jordan", phone: ["+962"], shortName: "JO", phoneLength: [9] },
  { name: "Kazakhstan", phone: ["+7-6", "+7-7"], shortName: "KZ", phoneLength: [10] },
  { name: "Kenya", phone: ["+254"], shortName: "KE", phoneLength: [9] },
  { name: "Kiribati", phone: ["+686"], shortName: "KI", phoneLength: [5] },
  { name: "Korea, North", phone: ["+850"], shortName: "KP", phoneLength: [9] },
  { name: "Korea, South", phone: ["+82"], shortName: "KR", phoneLength: [10] },
  { name: "Kosovo", phone: ["+383"], shortName: "XK", phoneLength: [8] },
  { name: "Kuwait", phone: ["+965"], shortName: "KW", phoneLength: [8] },
  { name: "Kyrgyzstan", phone: ["+996"], shortName: "KG", phoneLength: [9] },
  { name: "Laos", phone: ["+856"], shortName: "LA", phoneLength: [8] },
  { name: "Latvia", phone: ["+371"], shortName: "LV", phoneLength: [8] },
  { name: "Lebanon", phone: ["+961"], shortName: "LB", phoneLength: [8] },
  { name: "Lesotho", phone: ["+266"], shortName: "LS", phoneLength: [8] },
  { name: "Liberia", phone: ["+231"], shortName: "LR", phoneLength: [7] },
  { name: "Libya", phone: ["+218"], shortName: "LY", phoneLength: [9] },
  { name: "Liechtenstein", phone: ["+423"], shortName: "LI", phoneLength: [8] },
  { name: "Lithuania", phone: ["+370"], shortName: "LT", phoneLength: [8] },
  { name: "Luxembourg", phone: ["+352"], shortName: "LU", phoneLength: [9] },
  { name: "Madagascar", phone: ["+261"], shortName: "MG", phoneLength: [9] },
  { name: "Malawi", phone: ["+265"], shortName: "MW", phoneLength: [7] },
  { name: "Malaysia", phone: ["+60"], shortName: "MY", phoneLength: [10] },
  { name: "Maldives", phone: ["+960"], shortName: "MV", phoneLength: [7] },
  { name: "Mali", phone: ["+223"], shortName: "ML", phoneLength: [8] },
  { name: "Malta", phone: ["+356"], shortName: "MT", phoneLength: [8] },
  { name: "Marshall Islands", phone: ["+692"], shortName: "MH", phoneLength: [7] },
  { name: "Mauritania", phone: ["+222"], shortName: "MR", phoneLength: [8] },
  { name: "Mauritius", phone: ["+230"], shortName: "MU", phoneLength: [7] },
  { name: "Mexico", phone: ["+52"], shortName: "MX", phoneLength: [10] },
  { name: "Micronesia", phone: ["+691"], shortName: "FM", phoneLength: [7] },
  { name: "Moldova", phone: ["+373"], shortName: "MD", phoneLength: [8] },
  { name: "Monaco", phone: ["+377"], shortName: "MC", phoneLength: [9] },
  { name: "Mongolia", phone: ["+976"], shortName: "MN", phoneLength: [8] },
  { name: "Montenegro", phone: ["+382"], shortName: "ME", phoneLength: [8] },
  { name: "Morocco", phone: ["+212"], shortName: "MA", phoneLength: [10] },
  { name: "Mozambique", phone: ["+258"], shortName: "MZ", phoneLength: [9] },
  { name: "Myanmar", phone: ["+95"], shortName: "MM", phoneLength: [9] },
  { name: "Namibia", phone: ["+264"], shortName: "NA", phoneLength: [8] },
  { name: "Nauru", phone: ["+674"], shortName: "NR", phoneLength: [7] },
  { name: "Nepal", phone: ["+977"], shortName: "NP", phoneLength: [10] },
  { name: "Netherlands", phone: ["+31"], shortName: "NL", phoneLength: [10] },
  { name: "New Zealand", phone: ["+64"], shortName: "NZ", phoneLength: [9] },
  { name: "Nicaragua", phone: ["+505"], shortName: "NI", phoneLength: [8] },
  { name: "Niger", phone: ["+227"], shortName: "NE", phoneLength: [8] },
  { name: "Nigeria", phone: ["+234"], shortName: "NG", phoneLength: [10] },
  { name: "North Macedonia", phone: ["+389"], shortName: "MK", phoneLength: [8] },
  { name: "Norway", phone: ["+47"], shortName: "NO", phoneLength: [8] },
  { name: "Oman", phone: ["+968"], shortName: "OM", phoneLength: [8] },
  { name: "Pakistan", phone: ["+92"], shortName: "PK", phoneLength: [10] },
  { name: "Palau", phone: ["+680"], shortName: "PW", phoneLength: [7] },
  { name: "Palestine", phone: ["+970"], shortName: "PS", phoneLength: [9] },
  { name: "Panama", phone: ["+507"], shortName: "PA", phoneLength: [8] },
  { name: "Papua New Guinea", phone: ["+675"], shortName: "PG", phoneLength: [7] },
  { name: "Paraguay", phone: ["+595"], shortName: "PY", phoneLength: [9] },
  { name: "Peru", phone: ["+51"], shortName: "PE", phoneLength: [9] },
  { name: "Philippines", phone: ["+63"], shortName: "PH", phoneLength: [10] },
  { name: "Poland", phone: ["+48"], shortName: "PL", phoneLength: [9] },
  { name: "Portugal", phone: ["+351"], shortName: "PT", phoneLength: [9] },
  { name: "Qatar", phone: ["+974"], shortName: "QA", phoneLength: [8] },
  { name: "Romania", phone: ["+40"], shortName: "RO", phoneLength: [9] },
  { name: "Russia", phone: ["+7-0"], shortName: "RU", phoneLength: [10] },
  { name: "Rwanda", phone: ["+250"], shortName: "RW", phoneLength: [9] },
  { name: "Saint Kitts and Nevis", phone: ["+1-869"], shortName: "KN", phoneLength: [10] },
  { name: "Saint Lucia", phone: ["+1-758"], shortName: "LC", phoneLength: [10] },
  { name: "Saint Vincent and the Grenadines", phone: ["+1-784"], shortName: "VC", phoneLength: [10] },
  { name: "Samoa", phone: ["+685"], shortName: "WS", phoneLength: [7] },
  { name: "San Marino", phone: ["+378"], shortName: "SM", phoneLength: [9] },
  { name: "Sao Tome and Principe", phone: ["+239"], shortName: "ST", phoneLength: [7] },
  { name: "Saudi Arabia", phone: ["+966"], shortName: "SA", phoneLength: [9] },
  { name: "Senegal", phone: ["+221"], shortName: "SN", phoneLength: [9] },
  { name: "Serbia", phone: ["+381"], shortName: "RS", phoneLength: [9] },
  { name: "Seychelles", phone: ["+248"], shortName: "SC", phoneLength: [7] },
  { name: "Sierra Leone", phone: ["+232"], shortName: "SL", phoneLength: [8] },
  { name: "Singapore", phone: ["+65"], shortName: "SG", phoneLength: [8] },
  { name: "Slovakia", phone: ["+421"], shortName: "SK", phoneLength: [9] },
  { name: "Slovenia", phone: ["+386"], shortName: "SI", phoneLength: [8] },
  { name: "Solomon Islands", phone: ["+677"], shortName: "SB", phoneLength: [7] },
  { name: "Somalia", phone: ["+252"], shortName: "SO", phoneLength: [8] },
  { name: "South Africa", phone: ["+27"], shortName: "ZA", phoneLength: [9] },
  { name: "South Sudan", phone: ["+211"], shortName: "SS", phoneLength: [9] },
  { name: "Spain", phone: ["+34"], shortName: "ES", phoneLength: [9] },
  { name: "Sri Lanka", phone: ["+94"], shortName: "LK", phoneLength: [9] },
  { name: "Sudan", phone: ["+249"], shortName: "SD", phoneLength: [9] },
  { name: "Suriname", phone: ["+597"], shortName: "SR", phoneLength: [7] },
  { name: "Sweden", phone: ["+46"], shortName: "SE", phoneLength: [10] },
  { name: "Switzerland", phone: ["+41"], shortName: "CH", phoneLength: [9] },
  { name: "Syria", phone: ["+963"], shortName: "SY", phoneLength: [9] },
  { name: "Tajikistan", phone: ["+992"], shortName: "TJ", phoneLength: [9] },
  { name: "Tanzania", phone: ["+255"], shortName: "TZ", phoneLength: [10] },
  { name: "Thailand", phone: ["+66"], shortName: "TH", phoneLength: [9] },
  { name: "Timor-Leste", phone: ["+670"], shortName: "TL", phoneLength: [7] },
  { name: "Togo", phone: ["+228"], shortName: "TG", phoneLength: [8] },
  { name: "Tonga", phone: ["+676"], shortName: "TO", phoneLength: [5] },
  { name: "Trinidad and Tobago", phone: ["+1-868"], shortName: "TT", phoneLength: [10] },
  { name: "Tunisia", phone: ["+216"], shortName: "TN", phoneLength: [8] },
  { name: "Turkey", phone: ["+90"], shortName: "TR", phoneLength: [10] },
  { name: "Turkmenistan", phone: ["+993"], shortName: "TM", phoneLength: [8] },
  { name: "Tuvalu", phone: ["+688"], shortName: "TV", phoneLength: [5] },
  { name: "Uganda", phone: ["+256"], shortName: "UG", phoneLength: [9] },
  { name: "Ukraine", phone: ["+380"], shortName: "UA", phoneLength: [9] },
  { name: "United Arab Emirates", phone: ["+971"], shortName: "AE", phoneLength: [9] },
  { name: "United Kingdom", phone: ["+44"], shortName: "GB", phoneLength: [10] },
  { name: "United States", phone: ["+1"], shortName: "US", phoneLength: [10] },
  { name: "Uruguay", phone: ["+598"], shortName: "UY", phoneLength: [9] },
  { name: "Uzbekistan", phone: ["+998"], shortName: "UZ", phoneLength: [9] },
  { name: "Vanuatu", phone: ["+678"], shortName: "VU", phoneLength: [7] },
  { name: "Vatican City", phone: ["+379"], shortName: "VA", phoneLength: [8] },
  { name: "Venezuela", phone: ["+58"], shortName: "VE", phoneLength: [10] },
  { name: "Vietnam", phone: ["+84"], shortName: "VN", phoneLength: [9] },
  { name: "Yemen", phone: ["+967"], shortName: "YE", phoneLength: [9] },
  { name: "Zambia", phone: ["+260"], shortName: "ZM", phoneLength: [9] },
  { name: "Zimbabwe", phone: ["+263"], shortName: "ZW", phoneLength: [9] },
];